import { defineFigureCatalog } from "./catalog.js";
import type { FigureCatalogDefinition } from "./model.js";

export const ARCHITECTURE_CATALOG_ID = "system-architecture";

export const architectureCatalog: FigureCatalogDefinition = defineFigureCatalog({
  rootFigureId: "architecture-overview",
  figures: [
    {
      id: "architecture-overview",
      title: "Architecture spine",
      // The overview is an authored architecture map, not an arbitrary DAG.
      // Explicit positions keep the central spine dominant while preserving
      // room for the three system boundaries and the NodeUse continuation.
      layout: {
        kind: "explicit",
        positions: {
          "client-operations": { x: 0, y: 150 },
          "application-lifecycle": { x: 300, y: 150 },
          "workflow-server": { x: 600, y: 150 },
          "lifecycle-records": { x: 900, y: 0 },
          "runtime-providers": { x: 900, y: 150 },
          "core-runtime": { x: 900, y: 300 },
          "node-use": { x: 1200, y: 300 },
        },
      },
      nodes: [
        {
          id: "client-operations",
          label: "Front door and transport",
          summary: "Owner / agent -> CLI -> JSON-RPC",
          kind: "actor",
          icon: "network",
          evidencePointer: "docs/thesis/system-design-implementation.md#architecture-spine",
          childFigureId: "client-surface-detail",
        },
        {
          id: "application-lifecycle",
          label: "Workflow API operations",
          summary: "Capabilities, records, deployments, runs",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_api/service.py",
          childFigureId: "workflow-api-detail",
        },
        {
          id: "workflow-server",
          label: "WorkflowServer composition",
          summary: "API + records + inventory + kernel",
          kind: "runtime",
          icon: "server",
          evidencePointer: "src/wf_server/context.py",
          childFigureId: "runtime-provider-detail",
        },
        {
          id: "core-runtime",
          label: "wf_core execution loop",
          summary: "Select, dispatch, trace, route, resume",
          kind: "loop",
          icon: "repeat",
          evidencePointer: "src/wf_core/runtime/step.py",
          childFigureId: "core-runtime-detail",
        },
        {
          id: "lifecycle-records",
          label: "Lifecycle records",
          summary: "Drafts / artifacts / deployments / runs",
          kind: "artifact",
          icon: "database",
          evidencePointer: "src/wf_api/service.py",
          evidence: {
            label: "Durable boundary",
            title: "Lifecycle records",
            body: "The application surface persists and inspects each lifecycle record around runtime execution.",
            facts: [
              { label: "Records", value: "Draft, Artifact, Deployment, Run" },
              { label: "Runtime output", value: "Status, output, trace" },
            ],
            codePointer: "src/wf_api/service.py",
          },
        },
        {
          id: "runtime-providers",
          label: "Capability inventory",
          summary: "Provider-neutral CapabilitySource map",
          kind: "boundary",
          icon: "layers",
          evidencePointer: "src/wf_platform/sources.py",
          childFigureId: "runtime-provider-detail",
        },
        {
          id: "node-use",
          label: "NodeUse sequence",
          summary: "Bindings -> handler -> state -> trace",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_core/runtime/ops/nodes.py",
          childFigureId: "node-use-detail",
        },
      ],
      edges: [
        { id: "e-front-door-api", from: "client-operations", to: "application-lifecycle", label: "calls" },
        { id: "e-api-server", from: "application-lifecycle", to: "workflow-server", label: "composes" },
        { id: "e-server-core", from: "workflow-server", to: "core-runtime", label: "executes" },
        { id: "e-server-records", from: "workflow-server", to: "lifecycle-records", label: "persists" },
        { id: "e-server-inventory", from: "workflow-server", to: "runtime-providers", label: "projects" },
        { id: "e-core-node", from: "core-runtime", to: "node-use", label: "dispatches" },
      ],
    },
    {
      id: "client-surface-detail",
      title: "Client surface",
      layout: { kind: "fan-in" },
      nodes: [
        {
          id: "workflow-owner",
          label: "Workflow owner",
          summary: "Human author / operator",
          kind: "actor",
          icon: "users",
          evidencePointer: "docs/thesis/system-design-implementation.md#introduction",
        },
        {
          id: "external-agent",
          label: "External LLM agent",
          summary: "Plans and operates workflows",
          kind: "actor",
          icon: "workflow",
          evidencePointer: "docs/thesis/system-design-implementation.md#introduction",
        },
        {
          id: "web-console",
          label: "Web console",
          summary: "React presentation client",
          kind: "actor",
          icon: "network",
          evidencePointer: "web/apps/console",
        },
        {
          id: "cli",
          label: "wf CLI",
          summary: "Human and agent command surface",
          kind: "boundary",
          icon: "terminal",
          evidencePointer: "src/wf_cli",
        },
        {
          id: "json-rpc",
          label: "JSON-RPC / local adapter",
          summary: "Transport boundary",
          kind: "boundary",
          icon: "network",
          evidencePointer: "src/wf_transport_rpc_http",
        },
        {
          id: "workflow-api",
          label: "WorkflowApi",
          summary: "Protocol-neutral application surface",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_api/service.py",
          evidence: {
            label: "Public contract",
            title: "WorkflowApi",
            body: "CLI, JSON-RPC, and the console converge on one application facade.",
            facts: [
              { label: "Owns", value: "Capabilities and lifecycle operations" },
              { label: "Does not own", value: "Transport protocol behavior" },
            ],
            codePointer: "src/wf_api/service.py",
          },
        },
      ],
      edges: [
        { id: "e-owner-cli", from: "workflow-owner", to: "cli", label: "operates" },
        { id: "e-agent-cli", from: "external-agent", to: "cli", label: "operates" },
        { id: "e-console-rpc", from: "web-console", to: "json-rpc", label: "calls" },
        { id: "e-cli-rpc", from: "cli", to: "json-rpc", label: "uses" },
        { id: "e-rpc-api", from: "json-rpc", to: "workflow-api", label: "adapts" },
      ],
    },
    {
      id: "workflow-api-detail",
      title: "Workflow API operations",
      layout: { kind: "hub" },
      nodes: [
        {
          id: "workflow-api-boundary",
          label: "WorkflowApi boundary",
          summary: "Stable application facade",
          kind: "boundary",
          shape: "boundary",
          icon: "workflow",
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "capability-operations",
          label: "Capabilities",
          summary: "Discover and call workflow capabilities",
          kind: "operation",
          icon: "plug",
          details: [
            { label: "Methods", value: "list / inspect / call" },
            { label: "Input", value: "qualified name + payload" },
          ],
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "draft-operations",
          label: "Drafts",
          summary: "Validate, compile, patch authoring state",
          kind: "operation",
          icon: "layers",
          details: [{ label: "Methods", value: "validate / compile / patch" }],
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "artifact-operations",
          label: "Artifacts",
          summary: "Save immutable workflow versions",
          kind: "artifact",
          icon: "database",
          details: [{ label: "Methods", value: "create / inspect / delete" }],
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "deployment-operations",
          label: "Deployments",
          summary: "Bind artifacts to concrete sources",
          kind: "operation",
          icon: "network",
          details: [{ label: "Methods", value: "validate / save / inspect" }],
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "run-operations",
          label: "Runs",
          summary: "Start, resume, inspect execution",
          kind: "runtime",
          icon: "repeat",
          details: [{ label: "Methods", value: "start / resume / trace" }],
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "trace-output",
          label: "Trace and output",
          summary: "Bounded status / output / trace reads",
          kind: "evidence",
          icon: "trace",
          evidencePointer: "src/wf_api/runs.py",
        },
      ],
      edges: [
        { id: "e-capabilities-api", from: "capability-operations", to: "workflow-api-boundary" },
        { id: "e-drafts-api", from: "draft-operations", to: "workflow-api-boundary" },
        { id: "e-artifacts-api", from: "artifact-operations", to: "workflow-api-boundary" },
        { id: "e-deployments-api", from: "deployment-operations", to: "workflow-api-boundary" },
        { id: "e-runs-api", from: "run-operations", to: "workflow-api-boundary" },
        { id: "e-api-trace", from: "workflow-api-boundary", to: "trace-output", label: "returns" },
      ],
    },
    {
      id: "runtime-provider-detail",
      title: "WorkflowServer composition",
      layout: { kind: "hub" },
      nodes: [
        {
          id: "workflow-server",
          label: "WorkflowServer",
          summary: "Long-lived composition boundary",
          kind: "runtime",
          icon: "server",
          evidencePointer: "src/wf_server/context.py",
        },
        {
          id: "workflow-api",
          label: "WorkflowApi",
          summary: "Application operations",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "lifecycle-records",
          label: "Lifecycle records",
          summary: "Drafts / artifacts / deployments / runs",
          kind: "artifact",
          icon: "database",
          evidencePointer: "src/wf_api/service.py",
        },
        {
          id: "core-runtime",
          label: "wf_core",
          summary: "Deterministic execution kernel",
          kind: "loop",
          icon: "repeat",
          evidencePointer: "src/wf_core/runtime/step.py",
          childFigureId: "core-runtime-detail",
        },
        {
          id: "configured-providers",
          label: "Capability inventory",
          summary: "Provider-neutral CapabilitySource map",
          kind: "provider",
          icon: "layers",
          evidencePointer: "src/wf_platform/sources.py",
          childFigureId: "configured-provider-detail",
        },
        {
          id: "status-output-trace",
          label: "Status / output / trace",
          summary: "Inspectable runtime result",
          kind: "evidence",
          icon: "trace",
          evidencePointer: "src/wf_api/runs.py",
        },
      ],
      edges: [
        { id: "e-server-api", from: "workflow-server", to: "workflow-api", label: "exposes" },
        { id: "e-server-records", from: "workflow-server", to: "lifecycle-records", label: "owns" },
        { id: "e-server-core", from: "workflow-server", to: "core-runtime", label: "runs" },
        { id: "e-server-providers", from: "workflow-server", to: "configured-providers", label: "composes" },
        { id: "e-core-output", from: "core-runtime", to: "status-output-trace", label: "produces" },
        { id: "e-api-output", from: "workflow-api", to: "status-output-trace", label: "returns" },
      ],
    },
    {
      id: "configured-provider-detail",
      title: "Configured provider boundary",
      layout: { kind: "fan-in" },
      nodes: [
        {
          id: "builtin-sources",
          label: "Built-in sources",
          summary: "wf.std / wf.recipes",
          kind: "provider",
          icon: "layers",
          evidencePointer: "src/wf_api/local_sources.py",
        },
        {
          id: "mcp-sources",
          label: "MCP sources",
          summary: "wf_sources_mcp",
          kind: "provider",
          icon: "plug",
          evidencePointer: "src/wf_sources_mcp",
        },
        {
          id: "python-sources",
          label: "Python sources",
          summary: "wf_sources_python",
          kind: "provider",
          icon: "code",
          evidencePointer: "src/wf_sources_python",
        },
        {
          id: "capability-inventory",
          label: "Capability inventory",
          summary: "One provider-neutral CapabilitySource map",
          kind: "boundary",
          shape: "boundary",
          icon: "layers",
          evidencePointer: "src/wf_platform/sources.py",
          evidence: {
            label: "Neutral boundary",
            title: "CapabilitySource inventory",
            body: "Built-in, MCP, and Python providers project into one workflow-facing source inventory.",
            facts: [
              { label: "Core sees", value: "NodeSpec capabilities" },
              { label: "Provider logic", value: "Stays outside wf_core" },
            ],
            codePointer: "src/wf_server/sources.py",
          },
        },
        {
          id: "source-resolution",
          label: "Logical source resolution",
          summary: "Deployment binding selects a concrete source",
          kind: "operation",
          icon: "network",
          evidencePointer: "src/wf_api",
        },
      ],
      edges: [
        { id: "e-builtins-inventory", from: "builtin-sources", to: "capability-inventory", label: "projects" },
        { id: "e-mcp-inventory", from: "mcp-sources", to: "capability-inventory", label: "projects" },
        { id: "e-python-inventory", from: "python-sources", to: "capability-inventory", label: "projects" },
        { id: "e-inventory-resolution", from: "capability-inventory", to: "source-resolution", label: "resolves" },
      ],
    },
    {
      id: "core-runtime-detail",
      title: "wf_core execution loop",
      layout: { kind: "flow" },
      nodes: [
        {
          id: "validate-input",
          label: "Validate workflow input",
          summary: "Typed input contract",
          kind: "operation",
          icon: "workflow",
          shape: "receipt",
          evidencePointer: "src/wf_core/runtime/preparation.py",
        },
        {
          id: "select-frame",
          label: "Select ready frame",
          summary: "Scheduler chooses the next frame",
          kind: "runtime",
          icon: "repeat",
          evidencePointer: "src/wf_core/runtime/scheduler.py",
        },
        {
          id: "dispatch-step-kind",
          label: "Step kind",
          summary: "Typed dispatch",
          kind: "decision",
          icon: "branch",
          shape: "diamond",
          evidencePointer: "src/wf_core/runtime/step.py",
          childFigureId: "step-kind-detail",
        },
        {
          id: "execute-step",
          label: "Execute selected step",
          summary: "Typed handler returns a step result",
          kind: "operation",
          icon: "workflow",
          shape: "sequence",
          evidencePointer: "src/wf_core/models/steps.py",
        },
        {
          id: "append-trace",
          label: "Append trace frame",
          summary: "Record step result and lineage",
          kind: "evidence",
          icon: "trace",
          shape: "receipt",
          evidencePointer: "src/wf_core/runtime/ops/flow.py",
        },
        {
          id: "route-outcome",
          label: "Route by outcome",
          summary: "Next edge or terminal path",
          kind: "operation",
          icon: "network",
          evidencePointer: "src/wf_core/runtime/step.py",
        },
        {
          id: "persist-interrupt",
          label: "Persist interrupt request",
          summary: "Typed request and resume contract",
          kind: "evidence",
          icon: "pause",
          shape: "receipt",
          evidencePointer: "src/wf_core/runtime/ops/interrupts.py",
        },
        {
          id: "resume-payload",
          label: "Resume payload",
          summary: "Resume outcome returns to routing",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_core/runtime/preparation.py",
        },
        {
          id: "terminal-output",
          label: "Terminal output",
          summary: "Status, output, and final trace",
          kind: "terminal",
          icon: "stop",
          shape: "terminal",
          evidencePointer: "src/wf_core/runtime/step.py",
        },
      ],
      edges: [
        { id: "e-validate-select", from: "validate-input", to: "select-frame", label: "ready" },
        { id: "e-select-dispatch", from: "select-frame", to: "dispatch-step-kind", label: "dispatch" },
        { id: "e-dispatch-execute", from: "dispatch-step-kind", to: "execute-step", label: "step" },
        { id: "e-execute-trace", from: "execute-step", to: "append-trace", label: "result" },
        { id: "e-trace-route", from: "append-trace", to: "route-outcome", label: "recorded" },
        { id: "e-dispatch-interrupt", from: "dispatch-step-kind", to: "persist-interrupt", label: "interrupt" },
        { id: "e-persist-resume", from: "persist-interrupt", to: "resume-payload", label: "resume" },
        { id: "e-resume-route", from: "resume-payload", to: "route-outcome", label: "outcome" },
        { id: "e-dispatch-end", from: "dispatch-step-kind", to: "terminal-output", label: "end" },
      ],
    },
    {
      id: "step-kind-detail",
      title: "Supported step kinds",
      layout: {
        kind: "explicit",
        positions: {
          "node-use": { x: 0, y: 0 },
          "condition": { x: 300, y: 0 },
          "foreach": { x: 600, y: 0 },
          "join": { x: 900, y: 0 },
          "subgraph": { x: 150, y: 210 },
          "interrupt": { x: 450, y: 210 },
          "end": { x: 750, y: 210 },
        },
      },
      nodes: [
        {
          id: "node-use",
          label: "NodeUse",
          summary: "Invoke a bound capability",
          kind: "operation",
          icon: "workflow",
          evidencePointer: "src/wf_core/models/steps.py",
          childFigureId: "node-use-detail",
        },
        { id: "condition", label: "Condition", summary: "Route true or false", kind: "decision", icon: "branch", evidencePointer: "src/wf_core/models/steps.py" },
        { id: "foreach", label: "Foreach", summary: "Create item frames and barrier", kind: "loop", icon: "repeat", evidencePointer: "src/wf_core/models/steps.py" },
        { id: "join", label: "Join", summary: "Close a branch or frame", kind: "operation", icon: "workflow", evidencePointer: "src/wf_core/models/steps.py" },
        { id: "subgraph", label: "Subgraph", summary: "Enter a prepared child workflow", kind: "boundary", icon: "layers", evidencePointer: "src/wf_core/models/steps.py" },
        { id: "interrupt", label: "Interrupt", summary: "Persist request and wait", kind: "boundary", icon: "pause", evidencePointer: "src/wf_core/models/steps.py", childFigureId: "interrupt-contract-detail" },
        { id: "end", label: "End", summary: "Project a terminal outcome", kind: "terminal", icon: "stop", evidencePointer: "src/wf_core/models/steps.py" },
      ],
      edges: [],
    },
    {
      id: "interrupt-contract-detail",
      title: "Typed interrupt contract",
      layout: { kind: "hub" },
      nodes: [
        {
          id: "interrupt-request",
          label: "Request schema",
          summary: "Payload sent to the client",
          kind: "boundary",
          icon: "pause",
          evidencePointer: "src/wf_core/models/steps.py",
        },
        {
          id: "interrupt-resume",
          label: "Resume schema",
          summary: "Payload committed back to state",
          kind: "boundary",
          icon: "workflow",
          evidencePointer: "src/wf_core/models/steps.py",
        },
        {
          id: "interrupt-outcome",
          label: "Resume outcome",
          summary: "Declared route returns to the loop",
          kind: "operation",
          icon: "network",
          evidencePointer: "src/wf_core/runtime/preparation.py",
        },
      ],
      edges: [
        { id: "e-request-resume", from: "interrupt-request", to: "interrupt-resume", label: "validates" },
        { id: "e-resume-outcome", from: "interrupt-resume", to: "interrupt-outcome", label: "routes" },
      ],
    },
    {
      id: "node-use-detail",
      title: "NodeUse execution sequence",
      layout: {
        kind: "explicit",
        positions: {
          "runtime-lane": { x: 0, y: 120 },
          "binding-resolver": { x: 310, y: 120 },
          "node-def-handler": { x: 620, y: 120 },
          "state-reducers": { x: 930, y: 120 },
          "trace-store": { x: 1240, y: 120 },
        },
      },
      nodes: [
        {
          id: "runtime-lane",
          label: "Runtime",
          summary: "Validate input; select frame",
          kind: "runtime",
          shape: "sequence",
          icon: "server",
          evidence: {
            label: "Runtime frame",
            title: "Workflow Runtime",
            body: "The runtime selects a ready frame and coordinates the NodeUse branch.",
            facts: [{ label: "Next", value: "Outcome routing" }],
            codePointer: "src/wf_core/runtime/step.py",
          },
        },
        {
          id: "binding-resolver",
          label: "Binding Resolver",
          summary: "Build local node input",
          kind: "operation",
          shape: "sequence",
          icon: "network",
          evidence: {
            label: "Input",
            title: "Binding resolution",
            body: "Input bindings read workflow input, state, context, or literals into the node-local payload.",
            facts: [{ label: "Result", value: "Local node input" }],
            codePointer: "src/wf_core/runtime/ops/nodes.py",
          },
        },
        {
          id: "node-def-handler",
          label: "NodeDef Handler",
          summary: "Invoke the capability handler",
          kind: "operation",
          shape: "sequence",
          icon: "plug",
          evidence: {
            label: "Handler result",
            title: "NodeDef invocation",
            body: "The declared node definition handler returns an outcome and output payload.",
            facts: [{ label: "Result", value: "Outcome + output payload" }],
            codePointer: "src/wf_core/runtime/ops/nodes.py",
          },
        },
        {
          id: "state-reducers",
          label: "State Reducers",
          summary: "Apply declared output writes",
          kind: "artifact",
          shape: "sequence",
          icon: "database",
          evidence: {
            label: "State",
            title: "Reducer-aware state writes",
            body: "Successful output bindings merge the node result into workflow state.",
            facts: [{ label: "Write", value: "Reducer-aware output binding" }],
            codePointer: "src/wf_core/runtime/ops/state.py",
          },
        },
        {
          id: "trace-store",
          label: "Trace Store",
          summary: "Append frame and route outcome",
          kind: "evidence",
          shape: "sequence",
          icon: "trace",
          evidence: {
            label: "Inspection evidence",
            title: "Trace frame",
            body: "The completed step records its outcome, next node, and result before routing continues.",
            facts: [{ label: "Next", value: "Route by declared outcome" }],
            codePointer: "src/wf_core/runtime/ops/flow.py",
          },
        },
      ],
      edges: [
        { id: "e-runtime-bindings", from: "runtime-lane", to: "binding-resolver", label: "resolve input map" },
        { id: "e-bindings-handler", from: "binding-resolver", to: "node-def-handler", label: "local input" },
        { id: "e-handler-reducers", from: "node-def-handler", to: "state-reducers", label: "outcome + output" },
        { id: "e-reducers-trace", from: "state-reducers", to: "trace-store", label: "append frame" },
      ],
    },
  ],
});
